### ISSUE TITLE
Contribution Git Convention

### ISSUE THREAD

**Issue by KumKeeHyun** [jsoone24/EXT2_FILE_SYSTEM#12]
##
- master branch(root branch, release branch)
- master branch`s sub branch
  - dev branch(current default branch)
- dev branch`s sub branch
  - issue-{number}
- commit message
  - [issue-{number}] content

Develop issue-{number} branch and PR.

##
more information 
- issue : [issue-link](https://github.com/SSU-NC/toiot/issues)
- branch : [branch-link](https://github.com/SSU-NC/toiot/network)
  - 2020년 10월 이전 기록

**Comment by jsoone24** [comment]
??
